from prompts.utils.validator import PROFILE_VALIDATOR_PROMPT
from prompts.builder import (
    # Basic Profile
    BASIC_INFO_PROMPT,
    
    # Government
    GOVERNMENT_TYPE_PROMPT,
    LEADERSHIP_PROMPT,
    IDEOLOGIES_PROMPT,
    
    # Historical Context
    COLONIAL_HISTORY_PROMPT,
    MAJOR_CONFLICTS_PROMPT,
    FOREIGN_POLICY_PROMPT,
    
    # Foreign Policy
    CORE_GOALS_PROMPT,
    ALLIANCE_PROMPT,
    GLOBAL_ISSUES_PROMPT,
    TREATIES_PROMPT,
    
    # Economic Profile
    ECONOMIC_PROFILE_PROMPT,
    BACKUP_ECONOMIC_PROFILE_PROMPT,
    
    # Cultural & Societal
    CULTURAL_VALUES_PROMPT,
    PUBLIC_OPINION_PROMPT,
    COMMUNICATION_STYLE_PROMPT,
    BACKUP_CULTURAL_VALUES_PROMPT,
    BACKUP_CULTURAL_VALUES_PROMPT_GENERATE,
    
    # Diplomatic Behavior
    DIPLOMATIC_BEHAVIOR_PROMPT,
    BACKUP_DIPLOMATIC_BEHAVIOR_PROMPT,
    
    # Strategic Interests
    SECURITY_PROMPT,
    ECONOMIC_PROMPT,
    CULTURAL_PROMPT,
    BACKUP_STRATEGIC_INTERESTS_PROMPT,
    
    # Relationships & Alliances
    RELATIONSHIPS_AND_ALLIANCES_PROMPT,
    BACKUP_RELATIONSHIPS_AND_ALLIANCES_PROMPT,
    
    # Memory Seeds
    EVENTS_PROMPT,
    RESOLUTIONS_PROMPT,
    ALLIANCES_PROMPT,
    BACKUP_EVENTS_PROMPT,
    BACKUP_MEMORY_SEEDS_PROMPT
)

__all__ = [
    # Validator
    "PROFILE_VALIDATOR_PROMPT",
    
    # Basic Profile
    "BASIC_INFO_PROMPT",
    
    # Government
    "GOVERNMENT_TYPE_PROMPT",
    "LEADERSHIP_PROMPT",
    "IDEOLOGIES_PROMPT",
    
    # Historical Context
    "COLONIAL_HISTORY_PROMPT",
    "MAJOR_CONFLICTS_PROMPT",
    "FOREIGN_POLICY_PROMPT",
    
    # Foreign Policy
    "CORE_GOALS_PROMPT",
    "ALLIANCE_PROMPT",
    "GLOBAL_ISSUES_PROMPT",
    "TREATIES_PROMPT",
    
    # Economic Profile
    "ECONOMIC_PROFILE_PROMPT",
    "BACKUP_ECONOMIC_PROFILE_PROMPT",
    
    # Cultural & Societal
    "CULTURAL_VALUES_PROMPT",
    "PUBLIC_OPINION_PROMPT",
    "COMMUNICATION_STYLE_PROMPT",
    "BACKUP_CULTURAL_VALUES_PROMPT",
    "BACKUP_CULTURAL_VALUES_PROMPT_GENERATE",
    
    # Diplomatic Behavior
    "DIPLOMATIC_BEHAVIOR_PROMPT",
    "BACKUP_DIPLOMATIC_BEHAVIOR_PROMPT",
    
    # Strategic Interests
    "SECURITY_PROMPT",
    "ECONOMIC_PROMPT",
    "CULTURAL_PROMPT",
    "BACKUP_STRATEGIC_INTERESTS_PROMPT",
    
    # Relationships & Alliances
    "RELATIONSHIPS_AND_ALLIANCES_PROMPT",
    "BACKUP_RELATIONSHIPS_AND_ALLIANCES_PROMPT",
    
    # Memory Seeds
    "EVENTS_PROMPT",
    "RESOLUTIONS_PROMPT",
    "ALLIANCES_PROMPT",
    "BACKUP_EVENTS_PROMPT",
    "BACKUP_MEMORY_SEEDS_PROMPT"
]